<script>
var gv = {
  wsocket: undefined,
  leftDrawerOpen: false,
  manager: null,
  spider_progress: 0,
  current_sym_spidered: '',
  forbidSaveDB: true,
  db_LoadProgress: 0,
  scanning_progress: 0,
  scan_route_Tab: 'overall',
  scan_needRecheck_Tab: undefined,
  StockIndex: -1,
  Chart: undefined,
  P_Graph: undefined,
  graphSelected: false,
  code: 0,
  name: 1,
  dates: 2,
  values: 3,
  shares: 4,
  factors: 5,
  averages: 6,
  fuquan_averages: 7,
  topSeq: 8,
  bottomSeq: 9,
  graph: 10,
  shape: 0,
  left: 1,
  right: 2,
  top: 3,
  bottom: 4,
  hit_top: 5,
  hit_bottom: 6,
  level: 3,
  base: 4,
  slope: 5
}
var OverallSetting = {
  ScanDateStart: new Date(),
  ScanDateEnd: new Date(),
  prev: 2,
  prevMax: 10,
  prevMin: 2,
  next: 2,
  nextMax: 10,
  nextMin: 2,
  fuzzy: 0,
  fuzzyMax: 0.1,
  fuzzyMin: 0,
  minGLength: 22,
  minGLengthMax: 50,
  minGLengthMin: 22,
  maxGLength: 66,
  maxGLengthMax: 132,
  maxGLengthMin: 66
}
var RectangleSetting = {
  RectChecked: true,
  TopHits: 2,
  TopHitsMin: 2,
  TopHitsMax: 10,
  TopFuzzy: 0.5,
  TopFuzzyMin: 0.2,
  TopFuzzyMax: 1,
  BottomFuzzy: 0.5,
  BottomFuzzyMin: 0.2,
  BottomFuzzyMax: 1,
  BottomHits: 2,
  BottomHitsMin: 2,
  BottomHitsMax: 10,
  minHeight: 10,
  minHeightMax: 15,
  minHeightMin: 8,
  maxHeight: 25,
  maxHeightMax: 30,
  maxHeightMin: 15,
  rightMargin: 3,
  rightMarginMax: 10,
  rightMarginMin: 3,
  rightDrawback: 5,
  rightDrawbackMin: 3,
  rightDrawbackMax: 8
}

var TriangleUpSetting = {
  TriangleUpChecked: false,
  TopHits: 2,
  TopHitsMin: 2,
  TopHitsMax: 10,
  TopFuzzy: 0.5,
  TopFuzzyMin: 0.2,
  TopFuzzyMax: 1,
  BottomFuzzy: 0.5,
  BottomFuzzyMin: 0.2,
  BottomFuzzyMax: 1,
  BottomHits: 2,
  BottomHitsMin: 2,
  BottomHitsMax: 10,
  minHeight: 10,
  minHeightMax: 15,
  minHeightMin: 8,
  maxHeight: 25,
  maxHeightMax: 30,
  maxHeightMin: 15,
  rightMargin: 6,
  rightMarginMax: 10,
  rightMarginMin: 3,
  rightDrawback: 6,
  rightDrawbackMin: 3,
  rightDrawbackMax: 8,
  BottomSlope: 0.15,
  BottomSlopeMin: 0.05,
  BottomSlopeMax: 0.25
}
var TriangleDownSetting = {
  TriangleDownChecked: false,
  TopHits: 2,
  TopHitsMin: 2,
  TopHitsMax: 10,
  TopFuzzy: 0.5,
  TopFuzzyMin: 0.2,
  TopFuzzyMax: 1,
  BottomFuzzy: 0.5,
  BottomFuzzyMin: 0.2,
  BottomFuzzyMax: 1,
  BottomHits: 2,
  BottomHitsMin: 2,
  BottomHitsMax: 10,
  minHeight: 10,
  minHeightMax: 15,
  minHeightMin: 8,
  maxHeight: 25,
  maxHeightMax: 30,
  maxHeightMin: 15,
  rightMargin: 6,
  rightMarginMax: 10,
  rightMarginMin: 3,
  rightDrawback: 6,
  rightDrawbackMin: 3,
  rightDrawbackMax: 8,
  TopSlope: 0.15,
  TopSlopeMin: 0.05,
  TopSlopeMax: 0.25
}

var ScanGroup = []

export {gv, OverallSetting, RectangleSetting, TriangleUpSetting, TriangleDownSetting, ScanGroup}
</script>
